#!/bin/bash
set -euo pipefail

: "${APP_POSTGRES_DB:?APP_POSTGRES_DB is required}"
: "${APP_POSTGRES_RW_USER:?APP_POSTGRES_RW_USER is required}"
: "${APP_POSTGRES_RW_PASSWORD:?APP_POSTGRES_RW_PASSWORD is required}"
: "${APP_POSTGRES_RO_USER:?APP_POSTGRES_RO_USER is required}"
: "${APP_POSTGRES_RO_PASSWORD:?APP_POSTGRES_RO_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE "$APP_POSTGRES_DB";

    CREATE USER "$APP_POSTGRES_RW_USER" WITH PASSWORD '$APP_POSTGRES_RW_PASSWORD';
    CREATE USER "$APP_POSTGRES_RO_USER" WITH PASSWORD '$APP_POSTGRES_RO_PASSWORD';

    GRANT CONNECT ON DATABASE "$APP_POSTGRES_DB" TO "$APP_POSTGRES_RW_USER", "$APP_POSTGRES_RO_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS postgis;

    GRANT USAGE ON SCHEMA public TO "$APP_POSTGRES_RW_USER", "$APP_POSTGRES_RO_USER";

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$APP_POSTGRES_RW_USER";

    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "$APP_POSTGRES_RW_USER";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$APP_POSTGRES_RW_USER";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO "$APP_POSTGRES_RW_USER";

    GRANT SELECT ON ALL TABLES IN SCHEMA public TO "$APP_POSTGRES_RO_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT ON TABLES TO "$APP_POSTGRES_RO_USER";
EOSQL
